version: '3'

services:
    main:
        build: .
        volumes:
            - .:/app
        ports:
            - 3000:3000
        networks:
            - all
        environment:
            SERVICE_PORT: ${SERVICE_PORT}
            DATABASE_URL: ${DATABASE_URL}
        command: npm start

    mongo:
        image: mongo:3
        container_name: mongo
        command: mongod --smallfiles --bind_ip_all
        volumes:
            - ./data:/data/db
        restart: always
        ports:
            - "27017:27017"
        networks:
            - all
networks:
    all: